### ISSUE TITLE
Error while saving after accidental digestion begins

### ISSUE THREAD

**Issue by Garopen74924** [Error-String-Expected-Got-Nil/RV2-Esegn-Additions#2]
After the vore goal switches going from store goal to digest goal due to accidental digestion, if you save the game then load that save, then save again, this error pops up in the console while saving.
I'm wondering if its because of my specific setting config causing it. It doesn't matter whether digestion successfully finishes or if the prey is ejected, after accidental digestion begins the error will occur seemingly no matter what.
It seems like its not causing immediate problems, but I don't want to risk messing up my saves with the error.

![Screenshot](https://github.com/user-attachments/assets/6e9c8d2a-a5b2-4244-9533-c6c4fae2609d)
[Player.log](https://github.com/user-attachments/files/16920624/Player.log)

**Comment by Error-String-Expected-Got-Nil** [comment]
Huh, strange. Good news is though that that is a purely cosmetic issue- that code only relates to handling accidental digestion post-vore thoughts. You can keep playing without risk.

It's late for me right now but I can look into this tomorrow.

**Comment by Error-String-Expected-Got-Nil** [comment]
New release made, fixes issue. You can update on existing saves, won't cause any problems.
